# Generated by Django 3.2.23 on 2026-09-18 07:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('CL', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Current Listening')),
                ('CR', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Current Reading')),
                ('CW', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Current Writing')),
                ('CS', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Current Speaking')),
                ('CO', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Current Overall')),
                ('TL', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Targeted Listening')),
                ('TR', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Targeted Reading')),
                ('TW', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Targeted Writing')),
                ('TS', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Targeted Speaking')),
                ('TO', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Targeted Overall')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('preferred_theme', models.PositiveSmallIntegerField(choices=[(0, 'Light'), (1, 'Dark')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2'), ('full', 'Full test (Task 1 + Task 2)')], max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('task1_prompt', models.TextField(blank=True)),
                ('task1_image', models.ImageField(blank=True, null=True, upload_to='writing_prompts/')),
                ('task1_answer', models.TextField(blank=True)),
                ('task1_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_prompt', models.TextField(blank=True)),
                ('task2_answer', models.TextField(blank=True)),
                ('task2_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
