# Generated by Django 3.2.23 on 2026-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtest',
            name='task_type',
            field=models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2'), ('full', 'Full test (Task 1 + Task 2)')], default='task1', max_length=10),
        ),
    ]
