# Generated by Django 3.2.23 on 2026-09-18 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_writingtest_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
