# Generated by Django 3.2.23 on 2026-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260918_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtest',
            name='band',
            field=models.DecimalField(choices=[(9.0, '9.0 [39-40]'), (8.5, '8.5 [37-38]'), (8.0, '8.0 [35-36]'), (7.5, '7.5 [32-34]'), (7.0, '7.0 [30-31]'), (6.5, '6.5 [26-29]'), (6.0, '6.0 [23-25]'), (5.5, '5.5 [18-22]'), (5.0, '5.0 [16-17]'), (4.5, '4.5 [13-15]'), (4.0, '4.0 [11-12]'), (3.5, '3.5 [8-10]'), (3.0, '3.0 [6-7]'), (2.5, '2.5 [4-5]'), (2.0, '2.0 [3]'), (1.5, '1.5 [2]'), (1.0, '1.0 [1]'), (0.0, '0.0 [0]')], decimal_places=1, default=5.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='band',
            field=models.DecimalField(choices=[(9.0, '9.0 [39-40]'), (8.5, '8.5 [37-38]'), (8.0, '8.0 [35-36]'), (7.5, '7.5 [33-34]'), (7.0, '7.0 [30-32]'), (6.5, '6.5 [27-29]'), (6.0, '6.0 [23-26]'), (5.5, '5.5 [19-22]'), (5.0, '5.0 [15-18]'), (4.5, '4.5 [13-14]'), (4.0, '4.0 [10-12]'), (3.5, '3.5 [8-9]'), (3.0, '3.0 [6-7]'), (2.5, '2.5 [4-5]'), (2.0, '2.0 [3]'), (1.5, '1.5 [2]'), (1.0, '1.0 [1]'), (0.0, '0.0 [0]')], decimal_places=1, default=5.5, max_digits=3),
        ),
    ]
