# Generated by Django 3.2.23 on 2026-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20260918_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtest',
            name='task1_score',
            field=models.DecimalField(blank=True, choices=[(9.0, '9.0'), (8.5, '8.5'), (8.0, '8.0'), (7.5, '7.5'), (7.0, '7.0'), (6.5, '6.5'), (6.0, '6.0'), (5.5, '5.5'), (5.0, '5.0')], decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='task2_score',
            field=models.DecimalField(blank=True, choices=[(9.0, '9.0'), (8.5, '8.5'), (8.0, '8.0'), (7.5, '7.5'), (7.0, '7.0'), (6.5, '6.5'), (6.0, '6.0'), (5.5, '5.5'), (5.0, '5.0')], decimal_places=1, max_digits=3, null=True),
        ),
    ]
