# Generated by Django 3.2.23 on 2026-09-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260928_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, choices=[(9.0, '9.0'), (8.5, '8.5'), (8.0, '8.0'), (7.5, '7.5'), (7.0, '7.0'), (6.5, '6.5'), (6.0, '6.0'), (5.5, '5.5'), (5.0, '5.0')], decimal_places=1, max_digits=3, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
