# Generated by Django 3.2.23 on 2026-10-08 17:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_speakingtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtest',
            name='task1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='task1_image'),
        ),
    ]
